### ISSUE TITLE
ValueError raised if config attempts to include from "repo" that is not in "repos".

### ISSUE THREAD

**Issue by NGenetzky** [siemens/kas#25]
Also posted in [mailing list](https://groups.google.com/g/kas-devel/c/mKNx0kDnmAk).

---

Log for minimal example:

```
┌─[1] - [2020-10-09T10:04:36]
[pts/15][ngenetzky@ngenetzky-novo:/tmp/kas-bug-report][27593]
└─>( set -x && cat kas.yml && grep 'VERSION=' $(which kas-docker) && kas-docker shell ./kas.yml )                                                                                                              
+-zsh:20> cat kas.yml
header:
  version: 3
  includes:
    - repo: not-a-repo
      file: kas/board/qemux86-64.yml
repos:
  poky:
    url: git://git.yoctoproject.org/poky
    refspec: "51f6145f8f99a02df1dad937684f014b0172e72a" # yocto-2.6.4 # thud
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:
+-zsh:20> which kas-docker
+-zsh:20> grep '--color=auto' '--exclude-dir=.bzr' '--exclude-dir=CVS' '--exclude-dir=.git' '--exclude-dir=.hg' '--exclude-dir=.svn' '--exclude-dir=.idea' '--exclude-dir=.tox' 'VERSION=' /home/ngenetzky/.local/bin//kas-docker
        KAS_IMAGE_VERSION="2.1.1"
+-zsh:20> kas-docker shell ./kas.yml
2020-10-10 03:05:36 - INFO     - kas 2.1.1 started
2020-10-10 03:05:36 - INFO     - /repo$ git rev-parse --show-toplevel
2020-10-10 03:05:36 - INFO     - /repo$ hg root
2020-10-10 03:05:36 - ERROR    - Set of coroutines/Futures is empty.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/kas/kas.py", line 162, in main
    sys.exit(kas(sys.argv[1:]))
  File "/usr/local/lib/python3.7/dist-packages/kas/kas.py", line 150, in kas
    if plugin().run(args):
  File "/usr/local/lib/python3.7/dist-packages/kas/shell.py", line 112, in run
    macro.run(ctx, args.skip)
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 63, in run
    command.execute(ctx)
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 106, in execute
    while all(executor(c) for c in self.commands):
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 106, in <genexpr>
    while all(executor(c) for c in self.commands):
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 104, in executor
    return command.execute(ctx)
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 310, in execute
    repos_fetch(ctx.missing_repos)
  File "/usr/local/lib/python3.7/dist-packages/kas/libkas.py", line 171, in repos_fetch
    loop.run_until_complete(asyncio.wait(tasks))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/tasks.py", line 354, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/kas/kas.py", line 162, in main
    sys.exit(kas(sys.argv[1:]))
  File "/usr/local/lib/python3.7/dist-packages/kas/kas.py", line 150, in kas
    if plugin().run(args):
  File "/usr/local/lib/python3.7/dist-packages/kas/shell.py", line 112, in run
    macro.run(ctx, args.skip)
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 63, in run
    command.execute(ctx)
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 106, in execute
    while all(executor(c) for c in self.commands):
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 106, in <genexpr>
    while all(executor(c) for c in self.commands):
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 104, in executor
    return command.execute(ctx)
  File "/usr/local/lib/python3.7/dist-packages/kas/libcmds.py", line 310, in execute
    repos_fetch(ctx.missing_repos)
  File "/usr/local/lib/python3.7/dist-packages/kas/libkas.py", line 171, in repos_fetch
    loop.run_until_complete(asyncio.wait(tasks))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/asyncio/tasks.py", line 354, in wait
    raise ValueError('Set of coroutines/Futures is empty.')
ValueError: Set of coroutines/Futures is empty.
```

**Comment by NGenetzky** [comment]
Closed by [[PATCH] Report invalid repo key](https://groups.google.com/g/kas-devel/c/lPJdZOoPClM/m/lZI1P-XcAQAJ)
